name: React Native CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./amparo-front-end

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

        # --- PASSO DE DEBUG - ADICIONE ESTA PARTE ---
      - name: 🧐 Listar arquivos no repositório
        run: ls -R
        # Removemos o working-directory deste passo para ele rodar na raiz
        working-directory: ./ 
      # ---------------------------------------------

      - name: Setup do Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'amparo-front-end/package-lock.json'

      - name: Instalar dependências
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm run test